
const express = require('express');
const { generatePDFReportBuffer } = require('../services/pdfService');
const { generateSustainabilityInsight } = require('../services/geminiService');
const Report = require('../models/Report');
const Building = require('../models/Building');
const SustainabilityData = require('../models/SustainabilityData');
const { verifyToken } = require('../middleware/auth');

const router = express.Router();

// GET /api/reports - List past generated reports
router.get('/', async (req, res) => {
  try {
    const reports = await Report.find().sort({ createdAt: -1 });
    return res.json({ success: true, count: reports.length, data: reports });
  } catch (err) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// POST /api/reports/generate - Generate custom PDF report & stream download
router.post('/generate', async (req, res) => {
  try {
    const { title, reportType = 'Executive Summary', buildingIds, startDate, endDate } = req.body;

    const buildings = await Building.find(buildingIds && buildingIds.length ? { _id: { $in: buildingIds } } : {});

    // Real telemetry window - default last 30 days if no dates supplied
    const defaultStart = new Date();
    defaultStart.setDate(defaultStart.getDate() - 30);
    const rangeStart = startDate ? new Date(startDate) : defaultStart;
    const rangeEnd = endDate ? new Date(endDate) : new Date();

    const telemetryQuery = { timestamp: { $gte: rangeStart, $lte: rangeEnd } };
    if (buildingIds && buildingIds.length) {
      telemetryQuery.buildingId = { $in: buildingIds };
    }

    const telemetryRecords = await SustainabilityData.find(telemetryQuery);

    const totalElectricityKwh = telemetryRecords.reduce((acc, r) => acc + (r.electricityKwh || 0), 0);
    const totalWaterLiters = telemetryRecords.reduce((acc, r) => acc + (r.waterLiters || 0), 0);
    const totalCarbonKg = telemetryRecords.reduce((acc, r) => acc + (r.carbonKg || 0), 0);

    const allBuildingsForScore = buildings.length ? buildings : await Building.find();
    const sustainabilityScoreAvg = allBuildingsForScore.length
      ? Math.round(
        allBuildingsForScore.reduce((acc, b) => acc + (b.sustainabilityScore || 0), 0) / allBuildingsForScore.length
      )
      : 0;

    const anomalies = telemetryRecords.filter((r) => r.isAnomaly).map((r) => r.anomalyReason);

    // Ask Gemini (with automatic fallback) for a real executive summary + recommendations
    // based on the actual computed telemetry, instead of static hardcoded text
    const aiDataContext = {
      avgScore: sustainabilityScoreAvg,
      totalKwh: totalElectricityKwh,
      totalWater: totalWaterLiters,
      totalCarbon: totalCarbonKg,
      buildingCount: allBuildingsForScore.length,
      anomalies,
    };

    let executiveSummary = 'This PDF report provides real-time facility telemetry, scope 1-3 emission summaries, and AI optimization recommendations generated by EcoTwin AI Platform.';
    let recommendations = [
      'Set HVAC thermal setback of -2°C during non-occupancy hours across high-consumption buildings.',
      'Expand solar photovoltaic array coverage to increase grid offset.',
      'Investigate any flagged water flow anomalies for potential leaks.',
      'Upgrade smart waste bins to automatically notify facility staff at high volume capacity.',
    ];

    try {
      const insightRaw = await generateSustainabilityInsight(aiDataContext);
      const parsed = typeof insightRaw === 'string' && insightRaw.trim().startsWith('{') ? JSON.parse(insightRaw) : null;
      if (parsed) {
        if (parsed.summary) executiveSummary = parsed.summary;
        if (Array.isArray(parsed.recommendations) && parsed.recommendations.length) {
          recommendations = parsed.recommendations;
        }
      }
    } catch (aiErr) {
      console.warn('AI summary generation for report failed, using computed default text:', aiErr.message);
    }

    const reportData = {
      title: title || 'Campus Sustainability Performance & AI Audit',
      reportType,
      executiveSummary,
      totalElectricityKwh,
      totalWaterLiters,
      totalCarbonKg,
      sustainabilityScoreAvg,
      buildings: buildings.map((b) => ({
        name: b.name,
        code: b.code,
        areaSqFt: b.areaSqFt,
        status: b.status,
        score: b.sustainabilityScore,
      })),
      recommendations,
    };

    const pdfBuffer = await generatePDFReportBuffer(reportData);

    // Save report metadata log - now populates every real field the schema supports
    const reportLog = new Report({
      title: reportData.title,
      reportType,
      dateRange: {
        startDate: rangeStart.toISOString().split('T')[0],
        endDate: rangeEnd.toISOString().split('T')[0],
      },
      buildingsIncluded: buildings.map((b) => b._id),
      generatedBy: req.user && req.user._id ? req.user._id : undefined,
      summaryMetrics: {
        totalElectricityKwh: reportData.totalElectricityKwh,
        totalWaterLiters: reportData.totalWaterLiters,
        totalCarbonKg: reportData.totalCarbonKg,
        sustainabilityScoreAvg: reportData.sustainabilityScoreAvg,
      },
      executiveSummary: reportData.executiveSummary,
      recommendations: reportData.recommendations,
      fileSizeBytes: pdfBuffer.length,
    });
    await reportLog.save();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="EcoTwin_Report_${Date.now()}.pdf"`);
    return res.send(pdfBuffer);
  } catch (err) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;